# fly.toml app configuration file generated for jabble on 2024-06-18T22:32:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jabble'
primary_region = 'cdg'

[build]

[[mounts]]
source = 'db'
destination = '/db'

[http_service]
internal_port = 8081
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
