# https://github.com/F1bonacc1/process-compose#readme


environment:
  - "FORCE_COLOR=1"
processes:

  npm:
    command: bun install --color=always

  build:
    # initial mill build, so that vite finds the js files referenced in main.js
    command: |
      scripts/generate-query-code
      mill --jobs 0 --color true '{backend.compile,frontend.fastLinkJS}'

  vite:
    command: bunx vite dev --port 12345 --strictPort
    ports:
      - 12345:12345
    depends_on:
      npm:
        condition: process_completed_successfully
      build:
        # vite should start, even if the initial build failed
        condition: process_completed

  front:
    # frontend has separate mill watch process, because backend changes should not trigger page reloads
    command: mill --jobs 0 --color true --watch frontend.fastLinkJS
    env:
      LOG_LEVEL:debug
    depends_on:
      build:
        # watch should start, even if the initial build failed
        condition: process_completed

  back:
    # backend has separate mill watch process, because frontend changes should not trigger backend restarts
    command: mill --jobs 0 --color true --watch backend.runBackground
    env:
      LOG_LEVEL:debug
    depends_on:
      build:
        # watch should start, even if the initial build failed
        condition: process_completed

  query:
    command: find queries.sql schema.sql query_template.go.tmpl sqlc.yml | entr -npr scripts/generate-query-code

  rpc-re:
    # Workaround after changing sloth rpc api trait.
    # Somehow a change in the rpc trait is not detected by the compiler.
    # We need to clean and rebuild...
    # TODO: isolate and report bug
    command: find rpc | entr -np bash -c 'echo "cleaning rpc... (incremental compilation workaround)"; mill clean "{rpc,frontend,backend}"; touch rpc/src/rpc/RpcApi.scala'

  seed:
    command: echo schema.sql | entr -n bash -c "echo seeding database...; rm -f data.db; sqlite3 -init /dev/null data.db < schema.sql && echo success."

  auth:
    environment:
      - "APP_DOMAINS=$AUTHN_APP_DOMAINS"
      - "AUTHN_URL=https://ox-darling-heartily.ngrok-free.app"
      - "PORT=3001"
      - "PUBLIC_PORT=3000"
      - "SECRET_KEY_BASE=test"
      - "DATABASE_URL=sqlite3:///tmp/authn.db"
      - "ENABLE_SIGNUP=false"
      - "HTTP_AUTH_USERNAME=admin"
      - "HTTP_AUTH_PASSWORD=adminpw"
      - "TWITTER_OAUTH_CREDENTIALS=$AUTHN_TWITTER_OAUTH_CREDENTIALS"
    command: |
      # https://github.com/keratin/authn-server/tree/main/docs#readme
      ../authn-server/authn-server migrate && \
      ../authn-server/authn-server server

