#!/usr/bin/env bash

set -Eeuo pipefail

exitCode=0

migrations_path="./backend/resources/migrations"
schema_path="./schema.sql"

target_db_path="${migrations_path}/diff.target.db"
reference_db_path="${migrations_path}/diff.reference.db"

rm -f "${target_db_path}" "${reference_db_path}" "${target_db_path}.schema" "${reference_db_path}.schema"

echo "Set up reference database from schema file"
cat "$schema_path" | sqlite3 "${reference_db_path}"

echo "Set up target database by running all migrations"
find "${migrations_path}" -maxdepth 1 -type f -name "*.sql" -print0 | sort -z -n | xargs -0 awk 'ENDFILE {print ";"} 1' | sqlite3 "${target_db_path}"

echo "Diff the final state after migration with schemacrawler"
schemacrawler --server=sqlite --database=${target_db_path} --command=details --info-level=detailed | grep -v "^generated on" > ${target_db_path}.schema
schemacrawler --server=sqlite --database=${reference_db_path} --command=details --info-level=detailed | grep -v "^generated on" > ${reference_db_path}.schema
diff ${target_db_path}.schema ${reference_db_path}.schema && echo "All good. Migrations produce the desired schema!" || exitCode=$?

rm "${target_db_path}" "${reference_db_path}" "${target_db_path}.schema" "${reference_db_path}.schema"

exit $exitCode
