#!/usr/bin/env bash

set -Eeuo pipefail

# TODO: read directly from sqlc.yml using yq
targetDir="backend/src/backend/queries"

echo "Linting queries..."
sqlc vet
echo "Generating query code..."
sqlc generate
